var ficheroDeDatos;var grupo;var segundogrupocargado=!1;var tercergrupocargado=!1;$(function(){$(window).scroll(function(){if(!segundogrupocargado|!tercergrupocargado){if($(window).scrollTop()+$(window).height()>$(document).height()-2){if(!segundogrupocargado){cargarSegundoGrupo()}else{if(!tercergrupocargado){cargarTercerGrupo()}}}}});$("#PrimerGrupo").hide();$("#SegundoGrupo").show();$("#TercerGrupo").hide();$("#0 button").click(function(){window.location.href="./html/pais.html"});$("#1 button").click(function(){window.location.href="./html/pais2.html"});$("#2 button").click(function(){window.location.href="./html/pais.html"});$("#SegundoGrupo").click(function(){if(!segundogrupocargado){cargarSegundoGrupo()}});$("#TercerGrupo").click(function(){if(!tercergrupocargado){cargarTercerGrupo()}});$("#volver").click(function(){volverAlIndice()})});function cargarPrimerGrupo(){$("#PrimerGrupo").hide();$("#SegundoGrupo").show();$("#TercerGrupo").hide();grupo=1-1;ficheroDeDatos="./data/Asia1.json";crearEstructura();tratarDatos()}
function cargarSegundoGrupo(){$("#viajes").append("<div class='row' id='3'></div>"+"<div class='row' id='4'></div>"+"<div class='row' id='5'></div>");$("#PrimerGrupo").hide();$("#SegundoGrupo").hide();$("#TercerGrupo").show();grupo=2-1;ficheroDeDatos="./data/Asia2.json";crearEstructura();tratarDatos();segundogrupocargado=!0}
function cargarTercerGrupo(){$("#viajes").append("<div class='row' id='6'></div>"+"<div class='row' id='7'></div>"+"<div class='row' id='8'></div>");$("#PrimerGrupo").show();$("#SegundoGrupo").hide();$("#TercerGrupo").hide();grupo=3-1;ficheroDeDatos="./data/Asia3.json";crearEstructura();tratarDatos();tercergrupocargado=!0}
function crearEstructura(){for(var i=0+3*grupo;i<3+3*grupo;i++){$("#"+i).empty().append("<br/>"+"<h3><span class='glyphicon glyphicon-send pais'></span></h3>"+"<br/><br/>"+"<img class='img-responsive center-block' />"+"<p class='piedefigura'></p>"+"<div class='entrada'></div>"+"<p><span class='fecha'></span></p>"+"<br/><br/>"+"<button type='button' class='btn-lg btn-primary' data-toggle='modal' data-target='#info'>información</button>"+"<br/><br/><br/><br/>")}}
function crearEstructura_pais(){$("#cadaPais").empty().append("<br/>"+"<h3><span class='glyphicon glyphicon-send pais'></span></h3>"+"<br/><br/>"+"<img class='img-responsive center-block' />"+"<p class='piedefigura'></p>"+"<section class='descripcion'></section>"+"<p class='mapa'></p>"+"<p><span class='fecha'></span></p>"+"<button type='button' class='btn-lg btn-primary' data-toggle='modal' data-target='#info' id='volver'>VOLVER</button>"+"<br/><br/><br/><br/>")}
function crearEstructura_pais2(){$("#cadaPais2").empty().append("<br/>"+"<h3><span class='glyphicon glyphicon-send pais'></span></h3>"+"<br/><br/>"+"<img class='img-responsive center-block' />"+"<p class='piedefigura'></p>"+"<section class='descripcion'></section>"+"<p class='mapa'></p>"+"<p><span class='fecha'></span></p>"+"<button type='button' class='btn-lg btn-primary' data-toggle='modal' data-target='#info' id='volver'>VOLVER</button>"+"<br/><br/><br/><br/>")}
function tratarDatos(){$.getJSON(ficheroDeDatos,function(objeto){$.each(objeto,function(i,tupla){$("#"+(i+3*grupo)+" .pais").empty().append(tupla.pais);$("#"+(i+3*grupo)+" .fecha").empty().append(tupla.fecha);$("#"+(i+3*grupo)+" img").attr("src",tupla.fotografia);$("#"+(i+3*grupo)+" .piedefigura").empty().append(tupla.piedefigura);$("#"+(i+3*grupo)+" .entrada").empty().append(tupla.entrada);$("#"+(i+3*grupo)+" button").click(function(){window.location.href=tupla.enlace})})})};function tratarDatosPais(){$.getJSON("../data/Asia1.json",function(objeto){$("#cadaPais .pais").empty().append(objeto[0].pais);$("#cadaPais .fecha").empty().append(objeto[0].fecha);$("#cadaPais img").attr("src","../"+objeto[0].fotografia);$("#cadaPais .piedefigura").empty().append(objeto[0].piedefigura);$("#cadaPais .descripcion").empty().append(objeto[0].descripcion);$("#cadaPais .mapa").empty().append(objeto[0].mapa)})}
function tratarDatosPais2(){$.getJSON("../data/Asia1.json",function(objeto){$("#cadaPais2 .pais").empty().append(objeto[1].pais);$("#cadaPais2 .fecha").empty().append(objeto[1].fecha);$("#cadaPais2 img").attr("src","../"+objeto[1].fotografia);$("#cadaPais2 .piedefigura").empty().append(objeto[1].piedefigura);$("#cadaPais2 .descripcion").empty().append(objeto[1].descripcion);$("#cadaPais2 .mapa").empty().append(objeto[1].mapa)})}
function cargarPais(){crearEstructura_pais();tratarDatosPais();crearEstructura_pais2();tratarDatosPais2()}
function volverAlIndice(){window.location.href="../index.html"}
